<?php

return [
    'AGU' => 'Aguascalientes',
    'BC'  => 'Tijuana',
    'BCS' => 'La Paz',
    'CAM' => 'Campeche',
    'CHP' => 'Tuxtla Gutiérrez',
    'CHH' => 'Chihuahua',
    'COA' => 'Saltillo',
    'COL' => 'Colima',
    'DUR' => 'Durango',
    'GUA' => 'Chilpancingo', // Guerrero
    'GTO' => 'León',
    'HGO' => 'Pachuca',
    'JAL' => 'Guadalajara',
    'MEX' => 'Toluca',
    'MIC' => 'Morelia',
    'MOR' => 'Cuernavaca',
    'NAY' => 'Tepic',
    'NLE' => 'Monterrey',
    'OAX' => 'Oaxaca de Juárez',
    'PUE' => 'Puebla',
    'QUE' => 'Querétaro',
    'QR'  => 'Cancún',
    'SLP' => 'San Luis Potosí',
    'SIN' => 'Culiacán',
    'SON' => 'Hermosillo',
    'TAB' => 'Villahermosa',
    'TAM' => 'Tampico',
    'TLA' => 'Tlaxcala',
    'VER' => 'Veracruz',
    'YUC' => 'Mérida',
    'ZAC' => 'Zacatecas',
    'CDMX' => 'Mexico City',
];
